### ISSUE TITLE
Add Background Color 

### ISSUE THREAD

**Issue by Vente16** [remic-co/FindYourPet#9]
Add the background color to the component (Login).
The color for this component is: #e4e4e4
![background](https://user-images.githubusercontent.com/22964999/51805222-be6f7800-2238-11e9-860e-9dbc73221243.png)

**Comment by mateoguzmana** [comment]
Two things: 

- Please be more specific. To which component will be the background? Login? 
- Second, remember to add labels and assign this issue to a project. (In this case the Remic Board)

**Comment by Vente16** [comment]
Oh!, thank's for the recommendations
